# models/sources.yml

version: 2

sources:
  - name: raw # Logical name for your raw data source
    database: your_project_id # Your GCP project ID
    schema: your_raw_dataset_id # The BigQuery dataset where your raw data resides

    tables:
      - name: events # The actual table name in BigQuery (e.g., from your streaming ingestion)
        loaded_at_field: last_updated_at # The timestamp column in your source for freshness checks
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      # Add other raw source tables here, e.g.:
      # - name: products
      #   loaded_at_field: updated_at
      # - name: order_items_raw # Example for multiple key columns
      #   loaded_at_field: item_last_updated_at